apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openrum.fullname" . }}
  labels:
    {{- include "openrum.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  PUBLIC_BASE_URL: {{ .Values.config.publicBaseURL | quote }}
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  KAFKA_EVENT_TOPIC: {{ .Values.config.kafkaEventTopic | quote }}
  REDIS_ADDR: {{ .Values.config.redisAddress | quote }}
  OBJECT_STORAGE_PROVIDER: {{ .Values.config.objectStorage.provider | quote }}
  OBJECT_STORAGE_ENDPOINT: {{ .Values.config.objectStorage.endpoint | quote }}
  OBJECT_STORAGE_BUCKET: {{ .Values.config.objectStorage.bucket | quote }}
  OBJECT_STORAGE_REGION: {{ .Values.config.objectStorage.region | quote }}
  OBJECT_STORAGE_FORCE_PATH_STYLE: {{ .Values.config.objectStorage.forcePathStyle | quote }}
  OPENRUM_OBJECT_STORAGE_ENDPOINT_ALLOWLIST: {{ .Values.config.objectStorage.endpointAllowlist | quote }}
  OPENRUM_ALLOW_MANAGED_SECRETS: {{ .Values.config.managedSecrets.enabled | quote }}
  OPENRUM_MASTER_KEY_ID: {{ .Values.config.managedSecrets.masterKeyID | quote }}
