{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrum.fullname" $ }}-{{ $name }}
  labels:
    {{- include "openrum.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  selector:
    {{- include "openrum.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
